import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

// Preserve the actual license text and copyright notices of runtime dependencies.
const lock = JSON.parse(await readFile('package-lock.json', 'utf8'));
const sections = [
  'Codex Desk — Third-party notices',
  'Generated by scripts/notices.mjs from the locked production dependency graph.\n' +
    'Some packages are used only for type declarations. Electron and Chromium notices\n' +
    'are also distributed beside the executable in the desktop packages.',
];
for (const [directory, dependency] of Object.entries(lock.packages).sort(([a], [b]) => a.localeCompare(b))) {
  if (!directory || dependency.dev) continue;
  const pkg = JSON.parse(await readFile(path.join(directory, 'package.json'), 'utf8'));
  const files = (await readdir(directory))
    .filter((name) => /^(licen[sc]e|copying|notice)(\.|$)/i.test(name))
    .sort();
  if (!files.length) throw new Error(`License text missing for ${pkg.name}; review before packaging.`);
  sections.push(
    `${'='.repeat(72)}\n${pkg.name} ${dependency.version}\nLicense: ${dependency.license ?? pkg.license}\n`,
  );
  for (const file of files) sections.push(`${file}\n${await readFile(path.join(directory, file), 'utf8')}`);
}
await writeFile('THIRD_PARTY_NOTICES.txt', sections.join('\n\n').trimEnd() + '\n');
console.log('Updated THIRD_PARTY_NOTICES.txt');
